media: public
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view: 
      fields: [title, pubDate]
    fields:
        - {name: title, label: Title, type: string } 
        - {name: description, label: Description, type: string}
        - {name: pubDate, label: Date, type: string}
        - {name: heroImage, label: Image, type: string}
        - {name: body, label: Body, type: rich-text}